### ISSUE TITLE
Remove bootswatch style from all pages

### ISSUE THREAD

**Issue by jwillmer** [StarcounterPrefabs/UserAdmin#15]
Theming should only be applyed if not loaded in a launcher otherwise it will interfere with the theme of the launcher.

Since bootswatch is in every page referenced it would make sense to add it to the standalone page and remove it from every other page.

```<link rel="stylesheet" href="/sys/bootswatch/paper/bootstrap.css" />```

**Comment by warpech** [comment]
Taking this on me. This is what breaks styles in your Portal Launcher, obviously.

**Comment by warpech** [comment]
Closing as done. This will fix the top bar in Portal  when UserAdmin is running

![capture2](https://cloud.githubusercontent.com/assets/566463/17523293/5b4b8b96-5e5a-11e6-8ce7-af1ec23cc519.PNG)


cc @jwillmer, @aloscha, @Mnosek
