### ISSUE TITLE
UserAdmin doesn't work with SingIn application

### ISSUE THREAD

**Issue by aloscha** [StarcounterPrefabs/UserAdmin#24]
After running UserAdmin application and SingIn application I go to page `localhost/UserAdmin`, which redirect me to `localhost/signin/signinuser?originurl%3d%2fuseradmin%2fadmin%2fusers`.
I've seen blank page without errors and no more.

**Comment by warpech** [comment]
I managed to catch this on screenshot.

Steps to reproduce:

1. Start Launcher, SignIn, UserAdmin
2. Go to `localhost:8080/launcher` (not signed in)
3. Click on the UserAdmin icon in the launchpad
   - you will see a full-page sign in form
4. Provide sign in credentials in the full-page sign in form and press the Sign In button
   - you will see an exception, pictured below

![capture](https://cloud.githubusercontent.com/assets/566463/17705436/a586bf0e-63d8-11e6-97e8-f3fa97a0c12a.PNG)

**Comment by warpech** [comment]
Fixed
