### ISSUE TITLE
Automatically sign out in all browsers on password reset

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/UserAdmin#27]
It's a good security features, if an account gets compromised, than an admin might decide to reset password. In this case all user sessions should get expired.

Proposed by @jwillmer in https://github.com/StarcounterSamples/UserAdmin/issues/25.

**Comment by warpech** [comment]
@diliger could you take this? Sounds like a low-hanging fruit

**Comment by diliger** [comment]
I think to add a method `SignOutSystemUser(SystemUser User)` to Simplified and it will delete all tokens assigned to the **User**.

Is that a good solution?

**Comment by warpech** [comment]
Yes, I think that's a good idea.

**Comment by warpech** [comment]
Please verify how this affects GoogleSignIn app, though...

**Comment by diliger** [comment]
i'v pushed two PRs #54 and StarcounterPrefabs/Simplified/pull/44 check them please

and a question, after user get signed out, how can I force all pages to be updated automatically to show user is not authenticated?
because now it updates only on page reload.

**Comment by warpech** [comment]
> and a question, after user get signed out, how can I force all pages to be updated automatically to show user is not authenticated?
because now it updates only on page reload.

Each app needs to observe that on its own. I will make an issue about that in Guidelines: https://github.com/StarcounterPrefabs/Guidelines/issues/10

**Comment by diliger** [comment]
well, then it's out of scope of the current issue.

above you mentioned about `GoogleSignIn`, how should i test it?

**Comment by warpech** [comment]
Let's think about that first what is expected. Should changing password in SignIn app also log you out from sessions authenticated using other authentication methods?

I think **yes**, because this is what normally a user wants when they change password.

cc @joozek78

**Comment by joozek78** [comment]
Well, with new Authorization every action will be authorized, so no additional steps should be required (apart from removing the current session to log out the user).

It would be best to have an option to logout of all sessions when changing password (sometimes you just forget it, sometimes you fear it could be compromised). If we don't leave this choice to the user I'm positive that we should kill all sessions

**Comment by warpech** [comment]
Great! Then @diliger please check if changing password in UserAdmin also deauthenticates sessions authenticated with GoogleSignIn.

**Comment by warpech** [comment]
Solution is tracked in PR https://github.com/StarcounterPrefabs/UserAdmin/pull/54 and https://github.com/StarcounterPrefabs/Simplified/pull/44

**Comment by un-tone** [comment]
I found one strange thing regarding to the handler of the "Reset password". It requires the username to be an email.
![useradmin-resetpassword-disabled](https://cloud.githubusercontent.com/assets/1625378/22838685/603d65d4-efd7-11e6-912c-59a5474e92fa.png)
This behavior seems not obvious to me. I assume it should check a user's email instead of this `Utils.IsValidEmail(this.Data.Username)`.
Could someone confirm that it is a bug?

**Comment by warpech** [comment]
I guess at some point someone assumed that username equals email.

We can either change it to check the first EmailAddress of the Person assigned to the SystemUser, or add an EmailAddress property to SystemUser.

**Comment by warpech** [comment]
PR #54 and StarcounterPrefabs/Simplified#44 were merged.

Problem mentioned in https://github.com/StarcounterPrefabs/UserAdmin/issues/27#issuecomment-279026617 is tracked in https://github.com/StarcounterPrefabs/UserAdmin/issues/58

Closing as done
