### ISSUE TITLE
Rename 'Based on' to 'Belongs to' in the whole app

### ISSUE THREAD

**Issue by Mnosek** [StarcounterPrefabs/UserAdmin#29]
The 'Based on' field is a little bit misleading, it suggests that the child group has also parent privileges. In fact it means that the child group is a more specific group without inheritance of the privileges. Together with @miyconst we've agreed that this field should be renamed to 'Belongs to' to clarify. Issue covers changes in HTML, JSON and code behind files, there is no need to change anything in Simplified database classes.

**Comment by warpech** [comment]
I have renamed it in the UI, but not in property names. This will be refactored by @joozek78 eventually, so I better not mess with the code too much.
