### ISSUE TITLE
Move "System Settings" link from the menu to the Launcher settings page

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/UserAdmin#30]
Right now, the page that is used for the configuration of the UserAdmin app is accessible by the "System Settings" link in the Launcher's left menu.

This link should be removed.

The handler to that link needs to be mapped to `UriMapping.MappingUriPrefix + "/settings"`. Then, this page will be visible in the combined Launcher settings page.

See how this is done in the Images app: https://github.com/StarcounterPrefabs/Images/blob/6e0b6261221a1a6ac6cbd3d1ff7e53882609e330/src/Images/Api/MainHandlers.cs#L208

![screen shot 2016-08-17 at 18 01 02](https://cloud.githubusercontent.com/assets/566463/17743629/a5f66026-64a4-11e6-8e2f-a3cca1add761.png)

![screen shot 2016-08-17 at 17 59 25](https://cloud.githubusercontent.com/assets/566463/17743647/b4b7d374-64a4-11e6-9af9-dcbb5f3d0a13.png)

**Comment by Joltrix** [comment]
Implemented in PR #31

**Comment by warpech** [comment]
#31 merged
