### ISSUE TITLE
Replace the usage of the Page class with middleware

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/UserAdmin#33]
Please replace the usage of the Page class with middleware, since the Page class is obsolete (see Starcounter/Starcounter#3202). The instructions are in the blog post: http://starcounter.io/replace-page-partial-classes-middleware/

**Comment by diliger** [comment]
check please PR at #39

**Comment by warpech** [comment]
Done, merged. Thanks @diliger
