### ISSUE TITLE
Gravatar hash is incorectly calculated

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/UserAdmin#36]
### Steps to reproduce
1. Run User admin or inside.starcounter
2. Go to /UserAdmin/admin/users
3. Add user with email linked to gravatar
### Expected result

Gravatar image should be shown
### Actual result

Placeholder is shown
##### Browsers affected

all
### Screenshot

![image](https://cloud.githubusercontent.com/assets/17435/19173979/d7d60a2a-8c2b-11e6-8988-c15f03c8163c.png)

**Comment by warpech** [comment]
Not needed after https://github.com/StarcounterPrefabs/UserAdmin/issues/48

But thanks for reporting!
