### ISSUE TITLE
Move run.bat and build.bat to previous location

### ISSUE THREAD

**Issue by Mnosek** [StarcounterPrefabs/UserAdmin#45]
Those files should be placed as before - in main directory instead of src/UserAdmin. @andwah can you fix it please?

**Comment by andwah** [comment]
sure..

**Comment by andwah** [comment]
pull request created https://github.com/StarcounterPrefabs/UserAdmin/pull/46

Sorry for the messup.

**Comment by Mnosek** [comment]
Wow, thanks a lot for immediate fix! Closing this issue :)
