### ISSUE TITLE
Fix UI of the "Add" button

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/UserAdmin#55]
Right now it is not obvious, that the "Add" button is related to the dropdown that is above that button.

![perhapsthis](https://cloud.githubusercontent.com/assets/10708580/22819429/552afeaa-ef72-11e6-9b7e-02c4393422ef.gif)

The UI should be improved. I propose the following changes:

- put the "Add" button on the right of the dropdown and rename it to "Add to the group"
- rename "Add system group" to "Add to a system user group"

Then put al other buttons in a new line.

Source: https://github.com/Starcounter/CompanyTrack/issues/244

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterPrefabs/UserAdmin/pull/57

**Comment by un-tone** [comment]
Closing as done.
