### ISSUE TITLE
Create User Group button not working

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterPrefabs/UserAdmin#61]
GH Branch : Master
SC Version  : 2.3.0.5767

As soon as I click the button to create new user group An exception is generated, and page gets disconnected

![image](https://cloud.githubusercontent.com/assets/4388707/23512900/87f7e758-ff62-11e6-9d9e-18beead0fa79.png)

**Comment by warpech** [comment]
Fixed on `develop` branch. Please check
